### ISSUE TITLE
Generate CRUD resolvers based on the Prisma schema

### ISSUE THREAD

**Issue by pandaniell** [prisma/nexus-prisma#15]
It would be nice to have the option to generate CRUD resolvers based on our Prisma schema like [TypeGraphQL](https://typegraphql.com/docs/prisma.html) provides!

**Comment by kleydon** [comment]
+1, would love to see this.

**Comment by coopbri** [comment]
There is some more recent discussion about this here: https://github.com/graphql-nexus/nexus-prisma/issues/306

And some discussion worth looking at here: https://github.com/graphql-nexus/nexus-plugin-prisma/issues/1039

Temporarily, you can use the older `nexus-plugin-prisma` as described [here](https://graphql-nexus.github.io/nexus-prisma/docs/notes#nexus-plugin-prisma). Of course, this is not recommended (it is deprecated, and has not been updated for a couple years).

Personally, I ended up switching to Pothos with https://github.com/Cauen/prisma-generator-pothos-codegen, but would love to use Nexus instead of Pothos.

**Comment by kleydon** [comment]
@coopbri - thanks for the heads-up!
